version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - contextcheck
    - revive
    - sqlclosecheck
    - unconvert
  disable:
    - gocyclo
  settings:
    revive:
      rules:
        - name: context-as-argument
        - name: error-return
        - name: unused-parameter
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
